USE ETL_SQL
-- CRIANDO A PROCEDURE PARA ARMAZENAR TODO O SCRIPT	
CREATE OR ALTER PROCEDURE PROC_INSERT_TABELAS @CAMINHO VARCHAR(100)
AS
	DECLARE @COMANDO VARCHAR(MAX) = 

	'BULK INSERT HISTCASOSTRABALHADOS
	FROM ' + @CAMINHO + '
	WITH
	(
		FIELDTERMINATOR = '';''
		, CODEPAGE = ''65001''
		, FIRSTROW = 2
	)'

	EXECUTE ( @COMANDO )

	-- APAGANDO TABELAS ========================
	--  QUANDO RODAR VÁRIAS VEZES COMEÇA APAGANDO AS TABELAS (NÃO ICREMENTAL)
	TRUNCATE TABLE DIM_PAIS
	TRUNCATE TABLE DIM_CANAL_ENTRADA
	TRUNCATE TABLE DIM_STATUS
	TRUNCATE TABLE DIM_RESOLUCAO
	TRUNCATE TABLE DIM_MOTIVO_CHAMADOR
	TRUNCATE TABLE DIM_NOMEAGEN
	TRUNCATE TABLE DIM_NOMESUPE	
	TRUNCATE TABLE FATO
	

	-- INSERINDO DADOS NAS TABELAS ==============
	--  OS ID's SÃO AUTO ICREMENTAL
	INSERT INTO DIM_PAIS 
	SELECT DISTINCT
		PAÍS
	FROM
		HISTCASOSTRABALHADOS
	WHERE 
		PAÍS IS NOT NULL 
	
	INSERT INTO DIM_CANAL_ENTRADA 
	SELECT DISTINCT
		CANAL_ENTRADA
	FROM
		HISTCASOSTRABALHADOS
	WHERE 
		CANAL_ENTRADA IS NOT NULL 
	
	INSERT INTO DIM_STATUS
	SELECT DISTINCT
		[STATUS]
	FROM
		HISTCASOSTRABALHADOS
	WHERE 
		[STATUS] IS NOT NULL 
	
	INSERT INTO DIM_RESOLUCAO
	SELECT DISTINCT
		RESOLUÇÃO
	FROM
		HISTCASOSTRABALHADOS
	WHERE 
		RESOLUÇÃO IS NOT NULL 
	
	INSERT INTO DIM_MOTIVO_CHAMADOR
	SELECT DISTINCT
		MOTIVO_CHAMADOR
	FROM
		HISTCASOSTRABALHADOS
	WHERE 
		MOTIVO_CHAMADOR IS NOT NULL 

	INSERT INTO DIM_NOMEAGEN
	SELECT DISTINCT
		NOMEAGEN
	FROM
		HISTCASOSTRABALHADOS
	WHERE 
		NOMEAGEN IS NOT NULL 

	INSERT INTO DIM_NOMESUPE
	SELECT DISTINCT
		NOMESUPE
	FROM
		HISTCASOSTRABALHADOS
	WHERE 
		NOMESUPE IS NOT NULL 

	INSERT INTO FATO
	SELECT
		H.Id_Caso AS ID_CASO
		, P.ID AS ID_PAIS
		, CE.ID AS ID_CANAL_ENTRADA
		, S.ID AS ID_STATUS
		, R.ID AS ID_RESOLUCAO
		, M.ID AS ID_MOTIVO_CHAMADOR
		, NA.ID AS ID_NOME_AGEN
		, NS.ID AS ID_NOME_SUPE
		, H.Data_Hora_Criação AS DATA_CRIACAO
		, H.Data_Hora_Atualização AS DATA_ATUALIZACAO
		, H.Data_Hora_Fechamento AS DATA_FECHAMENTO
	FROM
		HISTCASOSTRABALHADOS H
	LEFT JOIN DIM_PAIS AS P
		ON P.PAIS = H.País
	LEFT JOIN DIM_CANAL_ENTRADA AS CE
		ON CE.CANAL_ENTRADA = H.Canal_Entrada
	LEFT JOIN DIM_MOTIVO_CHAMADOR M
		ON M.MOTIVO_CHAMADOR = H.Motivo_Chamador
	LEFT JOIN DIM_NOMEAGEN NA
		ON NA.NOMEAGEN = H.NomeAgen
	LEFT JOIN DIM_NOMESUPE NS
		ON NS.NOMESUPE = H.NomeSupe
	LEFT JOIN DIM_STATUS S
		ON S.[STATUS] = H.[Status]
	LEFT JOIN DIM_RESOLUCAO R
		ON R.RESOLUCAO = H.Resolução

-- APAGANDO A TABELA TRANSACIONAL
	TRUNCATE TABLE HISTCASOSTRABALHADOS		
GO


-- CHAMANDO A PROCEDURE PARA EXECUTAR A ETL
EXECUTE PROC_INSERT_TABELAS '[C:\Users\Lenovo\Desktop\SQL\ETL_SQL\BASE.csv]'