--CRIANDO O BANCO DE DADOS
--CREATE DATABASE ETL_SQL

-- USANDO/SELECIONANDO O BANCO DE DADOS
USE ETL_SQL

-- CRIANDO TABELA ONDE OS DADOS SERÃO INSERIDOS
--	TABELA PARA DADOS BRUTOS
CREATE TABLE HISTCASOSTRABALHADOS(
    ID_CASO VARCHAR(50)
    , PAÍS VARCHAR(5)
    , CANAL_ENTRADA VARCHAR(30)
    , [STATUS] VARCHAR(20)
    , RESOLUÇÃO VARCHAR(20)
    , MOTIVO_CHAMADOR VARCHAR(100)
    , NOMEAGEN VARCHAR(100)
    , NOMESUPE VARCHAR(100)
    , DATA_HORA_CRIAÇÃO DATETIME
    , DATA_HORA_ATUALIZAÇÃO DATETIME
    , DATA_HORA_FECHAMENTO DATETIME
)
GO

--================= NORMALIZAZÇÃO DA TABELA =========================

-- CRIANDO AS DIMENSÕES DA TABELA
--	AQUI A PK SERÁ INSERIDO AUTOMATICAMENTE 
CREATE TABLE DIM_PAIS(
	ID INT PRIMARY KEY IDENTITY (1,1)
	, PAIS CHAR(2) NOT NULL
)
GO

CREATE TABLE DIM_CANAL_ENTRADA(
	ID INT PRIMARY KEY IDENTITY (1,1)
	, CANAL_ENTRADA VARCHAR(10)
)
GO

CREATE TABLE DIM_STATUS(
	ID INT PRIMARY KEY IDENTITY (1,1)
	, STATUS VARCHAR(30)
)
GO

CREATE TABLE DIM_RESOLUCAO(
	ID INT PRIMARY KEY IDENTITY (1,1)
	, RESOLUCAO VARCHAR (5)
)
GO

CREATE TABLE DIM_MOTIVO_CHAMADOR(
	ID INT PRIMARY KEY IDENTITY (1,1)
	, MOTIVO_CHAMADOR VARCHAR (100)
)
GO

CREATE TABLE DIM_NOMEAGEN(
	ID INT PRIMARY KEY IDENTITY (1,1)
	, NOMEAGEN VARCHAR (100)
)
GO

CREATE TABLE DIM_NOMESUPE(
	ID INT PRIMARY KEY IDENTITY (1,1)
	, NOMESUPE VARCHAR (100)
)
GO

-- CRIANDO A TABELA FATO
--  TABELA NO FORMATO NORMALIZADO

CREATE TABLE FATO(
	ID INT PRIMARY KEY IDENTITY
	, ID_CASO VARCHAR(50)
	, ID_PAIS INT
	, ID_CANAL_ENTRADA INT
	, ID_STATUS INT
	, ID_RESOLUCAO INT
	, ID_MOTIVO_CHAMADOR INT
	, ID_NOME_AGEN INT
	, ID_NOME_SUPE INT
	, DATA_CRIACAO DATETIME
	, DATA_ATUALIZACAO DATETIME
	, DATA_FECHAMENTO DATETIME
)
GO
